### ISSUE TITLE
Change color scheme?

### ISSUE THREAD

**Issue by fzf** [unhappychoice/circleci-cli#30]
Let me first say that this is an awesome tool.

I was just wondering if there is some way to change the color scheme or where the colors come from. As you can see the black is pretty hard to read.

![Screen Shot 2019-09-23 at 11 49 47 AM](https://user-images.githubusercontent.com/1462357/65453579-589fb400-ddf8-11e9-8a9f-4991678d90b2.png)

**Comment by unhappychoice** [comment]
> Let me first say that this is an awesome tool.

Thank you and your notice :pray:

> black is pretty hard to read.

That's right. It's just a lock of consideration, so II'll change the color for title and labels. ( to normal white is good for that, I suppose.

**Comment by unhappychoice** [comment]
`2.1.0` release which has already published includes this changes.

**Comment by fzf** [comment]
Awesome! Thank you!
