### ISSUE TITLE
Watch specific branch

### ISSUE THREAD

**Issue by fzf** [unhappychoice/circleci-cli#34]
I am not sure if this is possible with the circle ci api but I was wondering if there is a way to watch a specific branch?

**Comment by unhappychoice** [comment]
I think we can :+1: 
So I will implement the option like `circle-cli watch -b branch_name` later ✋ .

**Comment by unhappychoice** [comment]
@all-contributors add @fzf for bug, ideas

**Comment by unhappychoice** [comment]
Released in https://github.com/unhappychoice/circleci-cli/blob/master/CHANGELOG.md#v220-2019-09-29

**Comment by fzf** [comment]
This is awesome, I realized that because I run a lot of pull requests off forked repos circle ci reports them as `branch: pull-request/1234` instead of the actual branch :( I made another pull request that lets you filter by the user that committed the code, happy to get your thoughts. This PR helped me understand what you were doing better. https://github.com/unhappychoice/circleci-cli/pull/44
